blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page, never_cache

from blog.views import ArticleListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('clients/', ArticleListView.as_view(), name='article_list'),
    path('clients/create/', never_cache(ArticleCreateView.as_view()), name='article_create'),
    path('clients/update/<int:pk>/', never_cache(ArticleUpdateView.as_view()), name='article_update'),
    path('clients/delete/<int:pk>/', never_cache(ArticleDeleteView.as_view()), name='article_delete'),
    path('clients/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='article_detail'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sender/', include('sender.urls', namespace='sender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('core.urls', namespace='core'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.apps import CoreConfig
from core.views import main_page

app_name = CoreConfig.name

urlpatterns = [
    path('', main_page, name='contacts'),
]

sender/urls.py
from django.urls import path
from sender.apps import SenderConfig
from sender.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingListView
from django.views.decorators.cache import cache_page, never_cache

app_name = SenderConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/', never_cache(ClientCreateView.as_view()), name='client_create'),
    path('clients/update/<int:pk>/', never_cache(ClientUpdateView.as_view()), name='client_update'),
    path('clients/delete/<int:pk>/', never_cache(ClientDeleteView.as_view()), name='client_delete'),
    path('clients/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', never_cache(MailingCreateView.as_view()), name='mailing_create'),
    path('mailings/update/<int:pk>/', never_cache(MailingUpdateView.as_view()), name='mailing_update'),
    path('mailings/delete/<int:pk>/', never_cache(MailingDeleteView.as_view()), name='mailing_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, UserLoginView

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),

    ]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from blog.models import Article
from sender.models import Mailing, Client, MailingMessage


@login_required()
def main_page(request):
    mailing_model = MailingMessage.objects.all().filter(user=request.user.pk)
    mailing_model_created = Mailing.objects.all().filter(status='Создана')
    client_model = Client.objects.filter(user=request.user.pk)
    articles_model = Article.objects.all()[:3]

    context = {
        'mailings': mailing_model,
        'active_mailings': mailing_model_created,
        'clients': client_model,
        'articles': articles_model
    }
    return render(request, 'core/main.html', context)

core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'color-modes.js' %}"></script>
    <title>{% block title %}Default title{% endblock title %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/pricing/">


    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}" sizes="180x180">
    <link rel="icon" href="{% static 'favicon-32x32.png' %}" sizes="32x32" type="image/png">
    <link rel="icon" href="{% static 'favicon-16x16.png' %}" sizes="16x16" type="image/png">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#712cf9">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'pricing.css' %}" rel="stylesheet">
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Изменить тему</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Светлая
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Темная
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Авто
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check" viewBox="0 0 16 16">
        <title>Check</title>
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
</svg>

<div class="container py-3">
    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 43 43">
                    <path fill="#BF6952"
                          d="M29 1c-4.139 0-6 3.509-6 6 0 2.57 2.43 5 5 5 1.92 0 3.468-1.28 3.766-3.113.232-1.426-.437-3.165-2.449-3.836-.528-.176-1.09.109-1.265.632-.175.524.108 1.09.632 1.265 1.174.391 1.166 1.262 1.107 1.618C29.68 9.257 29.071 10 28 10c-1.458 0-3-1.542-3-3 0-1.305.978-4 4-4 2.897 0 5 2.523 5 6v15c0 3.576-1.352 5.685-4.285 6.544.11-1.017.193-2.223.24-3.655.604-3.163.103-7.131-1.776-10.889-1.864-3.727-5.926-5.939-10.023-5.695C17.924 5.188 15.121 1 9.407 1 3.436 1 3.178 8 .178 12.399c-1.352 1.982 5.428 7.058 9.228 7.058l.043-.002c.352.029.801-.009 1.362-.13.57-.102 1.149-.268 1.719-.489 2.731-.835 4.376-.891 5.318-.443C17.137 21.761 14.027 24.621 12 28c-3 5 1 8 3 8 3 0 3-3 2-3-2 0-2.632-3.103-2-5 .658-1.974 2.609-3.521 3.871-6.053C18.608 23.627 18 25.543 18 27c0 4.568 1.17 6 6 6 .188 0 .36-.034.541-.052-.176.031-.354.052-.541.052-4.694 0-5.5.896-5.5 2 0 .809.5 1 1.5 1h7c.651 0 1.728-.003 2.398-3.321C33.782 31.756 36 28.848 36 24V9c0-4.561-3.01-8-7-8z"/>
                    <path fill="#D79E84"
                          d="M11.178 7.799C11.178 5.701 9.476 4 7.378 4c-2.1 0-3.801 1.701-3.801 3.799 0 .275.033.542.088.801-1.033.378-1.996 1.145-2.655 2.4-.255.486-.53.956-.832 1.399-.711 1.044.83 2.944 3.004 4.51 1.956 1.409 5.996.52 5.996-4.909 0-.29-.039-.561-.097-.821 1.239-.626 2.097-1.896 2.097-3.38zM13.822 6.5c0 1.933-.255 3.5 1.678 3.5 1.934 0 3.5-1.567 3.5-3.5S17.434 3 15.5 3c-1.933 0-1.678 1.567-1.678 3.5z"/>
                    <path fill="#292F33"
                          d="M7.435 8.371c0 .9-.485 1.629-1.085 1.629s-1.086-.729-1.086-1.629c0-.899.485-1.628 1.086-1.628.6 0 1.085.729 1.085 1.628z"/>
                    <path fill="#642116" d="M4 12c0 .552-2.17 2-3.085 2S0 13.552 0 13h.915C2.001 13 4 11.448 4 12z"/>
                </svg>
                <span class="fs-4">Сервис Skychimp</span>
            </a>

            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'sender:client_list' %}">Клиенты</a>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'sender:mailing_list' %}">Рассылки</a>
                {% if user.is_authenticated %}
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:profile' %}">Профиль</a>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:login' %}">Войти</a>
                    <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}

            </nav>
        </div>
    </header>

        {% block content %}
        {% endblock %}



    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <img class="mb-2" src="{% static 'skychimp.svg' %}" alt="" width="24" height="19">
                <small class="d-block mb-3 text-body-secondary">&copy; {% now 'Y' %}</small>
            </div>

            </div>

    </footer>
</div>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>

</body>
</html>

core/templates/core/main.html
{% extends 'core/base.html' %}
{% block title %}Главная{% endblock title %}
{% block header %}Главная{% endblock header %}
{% block content %}
     <div class="container d-flex justify-content-center align-items-center">
    <h1>Добро пожаловать!!</h1>
     </div>
    <div class="container d-flex justify-content-center align-items-center">

        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-4">
              <div class="card text-center">
                <div class="card-body">
                  <h5 class="card-title">Количество рассылок</h5>
                  <p class="card-text">{{ mailings.count }}</p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card text-center">
                <div class="card-body">
                  <h5 class="card-title">Активных рассылок</h5>
                  <p class="card-text">{{ active_mailings.count  }}</p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card text-center">
                <div class="card-body">
                  <h5 class="card-title">Количество клиентов</h5>
                  <p class="card-text">{{ clients.count }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="container d-flex justify-content-center align-items-center m-3">
    {% for article in articles %}
            <div class="col-5">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ article.title }}</h5>
                    </div>
                    <div class="card-body">
                        <img class="card-img" src="{{ article.image.url }}" alt="картинка">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>{{ article.content|truncatechars:100 }}</li>
                        </ul>
                        <div class="btn-group mb-2">
                              <a href="#" class="btn btn-sm btn-outline-primary">Читать</a>
                        </div>
                        <div class="card-footer">
                            Просмотры: {{ article.views }}
                        </div>
                    </div>
                </div>

    {% endfor %}
{% endblock content %}