blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page, never_cache

from blog.views import ArticleListView, ArticleCreateView, ArticleUpdateView, ArticleDeleteView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('clients/', ArticleListView.as_view(), name='article_list'),
    path('clients/create/', never_cache(ArticleCreateView.as_view()), name='article_create'),
    path('clients/update/<int:pk>/', never_cache(ArticleUpdateView.as_view()), name='article_update'),
    path('clients/delete/<int:pk>/', never_cache(ArticleDeleteView.as_view()), name='article_delete'),
    path('clients/<int:pk>/', cache_page(60)(ArticleDetailView.as_view()), name='article_detail'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sender/', include('sender.urls', namespace='sender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('core.urls', namespace='core'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sender/urls.py
from django.urls import path
from sender.apps import SenderConfig
from sender.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, \
    MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingListView
from django.views.decorators.cache import cache_page, never_cache

app_name = SenderConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/create/', never_cache(ClientCreateView.as_view()), name='client_create'),
    path('clients/update/<int:pk>/', never_cache(ClientUpdateView.as_view()), name='client_update'),
    path('clients/delete/<int:pk>/', never_cache(ClientDeleteView.as_view()), name='client_delete'),
    path('clients/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('mailings/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', never_cache(MailingCreateView.as_view()), name='mailing_create'),
    path('mailings/update/<int:pk>/', never_cache(MailingUpdateView.as_view()), name='mailing_update'),
    path('mailings/delete/<int:pk>/', never_cache(MailingDeleteView.as_view()), name='mailing_delete'),
]

sender/models.py
from django.db import models
from users.models import User
from datetime import date, datetime

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='имя')
    last_name = models.CharField(max_length=50, verbose_name='фамилия')
    patronymic = models.CharField(max_length=50, verbose_name='отчество')

    email = models.EmailField(max_length=150, verbose_name='почта')
    comment = models.TextField(verbose_name='комментарий')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь', blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name='активный')

    def __str__(self):
        return f'{self.first_name} ({self.email})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class MailingMessage(models.Model):
    subject = models.CharField(max_length=255, verbose_name='тема')
    body = models.TextField(verbose_name='текст письма')
    client = models.ManyToManyField(Client, verbose_name='клиент', blank=True, null=True, )
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='пользователь', blank=True, null=True,)
    created_at = models.DateTimeField(default=datetime.now, verbose_name='создано')

    def __str__(self):
        return f'{self.subject} {self.client}'

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'


class Mailing(models.Model):
    ONCE = 'разовая'
    DAILY = 'ежедневно'
    WEEKLY = 'еженедельно'
    MONTHLY = 'ежемесячно'

    SEND_PERIOD = [
        (ONCE, 'разовая'),
        (DAILY, 'ежедневно'),
        (WEEKLY, 'еженедельно'),
        (MONTHLY, 'ежемесячно'),
    ]

    CREATED = 'создана'
    COMPLETED = 'завершена'
    LAUNCHED = 'запущена'

    SELECT_STATUS = [
        (CREATED, 'создана'),
        (COMPLETED, 'завершена'),
        (LAUNCHED, 'запущена'),
    ]

    message = models.ForeignKey(MailingMessage, default=1, on_delete=models.CASCADE, verbose_name='сообщение')
    time = models.TimeField(default=datetime.now, verbose_name='время')
    start = models.DateTimeField(default=datetime.now, verbose_name='начало рассылки')
    finish = models.DateTimeField(default=datetime.now, verbose_name='окончание рассылки')
    send_period = models.CharField(max_length=150, choices=SEND_PERIOD, verbose_name='периодичность')
    status = models.CharField(max_length=100, default='начало рассылки', choices=SELECT_STATUS, verbose_name='статус')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE, verbose_name='создана')


    def __str__(self):
        return f'{self.time} - {self.send_period} - {self.status}'

    class Meta:
        verbose_name = 'настройка'
        verbose_name_plural = 'настройки'


class MailingLog(models.Model):
    DELIVERED = 'delivered'
    NOT_DELIVERED = 'not_delivered'

    STATUS = (
        (DELIVERED, 'доставлено'),
        (NOT_DELIVERED, 'не доставлено'),
    )

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='настройка')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='дата последней рассылки')
    status = models.CharField(choices=STATUS, max_length=255, verbose_name='статус')
    response = models.TextField(**NULLABLE, verbose_name='ответ сервера')

    def __str__(self):
        return f'{self.timestamp} - {self.status}'

    class Meta:
        verbose_name = 'попытка'
        verbose_name_plural = 'попытки'

sender/forms.py
from django import forms
from sender.models import Client, MailingMessage


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('first_name', 'last_name', 'patronymic', 'email', 'comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingMessageForm(forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = ('subject', 'body', 'client',)

    def clean_name(self):
        name = self.cleaned_data['name']
        if any(word in name.lower() for word in
               ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']):
            raise forms.ValidationError('Название продукта содержит запрещенные слова')
        return name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

sender/views.py
import django
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import modelformset_factory
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from sender.forms import ClientForm, MailingMessageForm
from sender.models import Client, MailingMessage, Mailing
from sender.services import send_email


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        return Client.objects.filter(user=self.request.user.pk)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('sender:client_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        product_formset = modelformset_factory(Client, form=ClientForm, extra=1)
        context_data['title'] = 'Добавить товар'
        if self.request.method == 'POST':
            context_data['formset'] = product_formset(self.request.POST)
        else:
            context_data['formset'] = product_formset()
        return context_data

    def form_valid(self, form):
        mailing = form.save()
        mailing.user = self.request.user
        mailing.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('sender:client_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        client_formset = modelformset_factory(Client, form=ClientForm, extra=1)
        context_data['title'] = 'Добавить товар'
        if self.request.method == 'POST':
            context_data['formset'] = client_formset(self.request.POST)
        else:
            context_data['formset'] = client_formset()
        return context_data


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Client
    permission_required = 'sender.delete_client'
    success_url = reverse_lazy('sender:client_list')



class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    success_url = reverse_lazy('sender:client_list')


class MailingListView(LoginRequiredMixin, ListView):
    model = MailingMessage

    def get_queryset(self):
        return MailingMessage.objects.filter(user=self.request.user.pk)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('sender:mailing_list')
    try:
        for mailing in Mailing.objects.all():
            if mailing.status == Mailing.CREATED:
                send_email(Mailing.ONCE)
    except django.db.utils.ProgrammingError:
        print('ProgrammingError')

    def form_valid(self, form):
        mailing = form.save()
        mailing.user = self.request.user
        mailing.save()
        send_email(mailing)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        mailing_message_formset = modelformset_factory(MailingMessage, form=MailingMessageForm, extra=1)
        context_data['title'] = 'Добавить рассылку'
        if self.request.method == 'POST':
            context_data['formset'] = mailing_message_formset(self.request.POST)
        else:
            context_data['formset'] = mailing_message_formset()
        return context_data


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('sender:mailing_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        mailing_message_formset = modelformset_factory(MailingMessage, form=MailingMessageForm, extra=1)
        context_data['title'] = 'Редактировать рассылку'
        if self.request.method == 'POST':
            context_data['formset'] = mailing_message_formset(self.request.POST)
        else:
            context_data['formset'] = mailing_message_formset()
        return context_data


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = MailingMessage
    permission_required = 'sender.delete_mailing'
    success_url = reverse_lazy('sender:mailing_list')


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = MailingMessage
    success_url = reverse_lazy('sender:mailing_list')

sender/templates/sender/client_confirm_delete.html
{% extends 'core/base.html' %}
{% block title %}Удаление клиента{% endblock title %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить клиента {{ object.last_name }} {{ object.first_name }}?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'sender:client_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sender/templates/sender/client_detail.html
{% extends 'core/base.html' %}
{% block title %}{{ object.first_name }} {{ object.last_name }}{% endblock title %}
{% block content %}
    <div class="col-md-12">
      <div class="card">
        <h1>{{ object.last_name }} {{ object.first_name }} {{ object.patronymic }}</h1>
        <h6>Почта: {{ object.email }}</h6>
        <p>Комментарий: {{ object.comment }}</p>
      </div>
    </div>
{% endblock %}

sender/templates/sender/client_form.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <div class="col-12 container d-flex justify-content-center align-items-center">
        <div class="row ">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sender/templates/sender/client_list.html
{% extends 'core/base.html' %}
{% block title %}Список клиентов{% endblock title %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center ">
            <h1 class="display-4 fw-normal text-body-emphasis">Клиенты</h1>
            <p class="fs-5 text-body-secondary">Создание и редактирование клиентов сервиса</p>
        </div>

    <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for object in object_list %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ object.first_name}} {{ object.last_name }}</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Отчество: {{ object.patronymic }}</li>
                            <li>Почта: {{ object.email }}</li>
                        </ul>
                        <div class="btn-group">
                              <a href="{% url 'sender:client_detail' object.pk %}" class="btn btn-sm btn-outline-primary">Просмотр</a>
                              <a href="{% url 'sender:client_update' object.pk %}" class="btn btn-sm btn-outline-primary">Редактировать</a>
                              <a href="{% url 'sender:client_delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">Новый клиент</h5>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-sm btn-outline-primary" href="{% url 'sender:client_create' %}">Добавить</a>
                    </div>
                </div>
            </div>
           </div>
    </main>
{% endblock %}

sender/templates/sender/mailingmessage_confirm_delete.html
{% extends 'core/base.html' %}
{% block title %}Удаление клиента{% endblock title %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить рассылку {{ object.subject }}?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'sender:client_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sender/templates/sender/mailingmessage_detail.html
{% extends 'core/base.html' %}
{% block title %}{{ object.subject }}{% endblock title %}
{% block content %}
    <div class="col-md-12">
      <div class="card">
        <h1>{{ object.subject }}</h1>
        <h6>{{ object.body }}</h6>
        <p>Клиент: {{ object.client }}</p>
      </div>
    </div>
{% endblock %}

sender/templates/sender/mailingmessage_form.html
{% extends 'core/base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    <div class="col-12 container d-flex justify-content-center align-items-center">
        <div class="row ">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Добавить
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sender/templates/sender/mailingmessage_list.html
{% extends 'core/base.html' %}
{% block title %}Список рассылок{% endblock title %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Рассылки</h1>
            <p class="fs-5 text-body-secondary">Создание и редактирование рассылок</p>
        </div>

    <main>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% for object in object_list %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">{{ object.subject}} </h5>
                    </div>
                    <div class="card-body">
                        <p>{{ object.body|truncatechars:100 }}</p>
                        <div class="btn-group">
                              <a href="{% url 'sender:mailing_detail' object.pk %}" class="btn btn-sm btn-outline-primary">Просмотр</a>
                              <a href="{% url 'sender:mailing_update' object.pk %}" class="btn btn-sm btn-outline-primary">Редактировать</a>
                              <a href="{% url 'sender:mailing_delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h5 class="my-0 fw-normal">Новая рассылка</h5>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-sm btn-outline-primary" href="{% url 'sender:mailing_create' %}">Добавить</a>
                    </div>
                </div>
            </div>
           </div>
    </main>
{% endblock %}